[package]
name = "compmode"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive", "env"] }
regex = "1.11.1"

[build-dependencies]
anyhow = "1.0.94"
vergen-git2 = { version = "1.0.0", features = [] }
